[package]
name = "httpretty"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
ratatui = { version = "0.26.1", features = ["all-widgets", "crossterm"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18" }
