[package]
name = "httpretty"
version = "0.1.0"
edition = "2021"

[dependencies]
config.workspace = true
anyhow.workspace = true
tracing.workspace = true

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
