[package]
name = "httpretty"
version = "0.1.0"
edition = "2021"

[dependencies]
config.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde_json.workspace = true
